[build]
  command   = "bun install --frozen-lockfile && bun run build"
  publish   = "dist"
  # Uncomment if using Netlify Functions:
  # functions = "netlify/functions"

[build.environment]
  NODE_ENV          = "production"
  NODE_VERSION      = "20"
  BUN_VERSION       = "1.2.19"
  NETLIFY_USE_BUN   = "true"
  # Add non-secret runtime defaults here if desired; keep real secrets in Netlify UI
  # VITE_API_URL    = "https://example.api"