// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udpilfxpsgyhbmjikuxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkcGlsZnhwc2d5aGJtamlrdXh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzODcyODIsImV4cCI6MjA3NDk2MzI4Mn0.VRWs9j1WT_fdY6JcNBM1BsOeVJC73XRR5GvZ6ScL8Cs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});