// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shcuzhyonrpacdynxjjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoY3V6aHlvbnJwYWNkeW54ampkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMzcxNzIsImV4cCI6MjA2NTgxMzE3Mn0._GF157A1ifzBSOvDbHgICOXWQhIz-wberdi8JWdBCC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});