# IPE Pillar 7: Implementation-ready CI/CD guardrails
name: Assessment Quality Assurance
permissions:
  contents: read

on:
  push:
    branches: [ main, develop ]
    paths: 
      - 'src/data/assessmentQuestions.ts'
      - 'src/types/assessment.ts'
      - 'src/components/LivingEnvironment*.tsx'
      - 'package.json'
      - 'bun.lockb'
      - 'package-lock.json'
      - 'pnpm-lock.yaml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/data/assessmentQuestions.ts'
      - 'src/types/assessment.ts'
      - 'src/components/LivingEnvironment*.tsx'
      - 'package.json'
      - 'bun.lockb'
      - 'package-lock.json'
      - 'pnpm-lock.yaml'

jobs:
  assessment-lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Validate single lockfile (Bun-only policy)
      run: |
        lockfile_count=0
        [ -f "bun.lockb" ] && lockfile_count=$((lockfile_count + 1))
        [ -f "package-lock.json" ] && lockfile_count=$((lockfile_count + 1))
        [ -f "pnpm-lock.yaml" ] && lockfile_count=$((lockfile_count + 1))
        [ -f "yarn.lock" ] && lockfile_count=$((lockfile_count + 1))
        
        if [ $lockfile_count -gt 1 ]; then
          echo "❌ Multiple lockfiles detected. Project uses Bun only."
          echo "Found lockfiles:"
          ls -la *lock* 2>/dev/null || true
          echo "Please remove all lockfiles except bun.lockb"
          exit 1
        elif [ $lockfile_count -eq 0 ]; then
          echo "❌ No lockfile found. Please run 'bun install' to generate bun.lockb"
          exit 1
        elif [ ! -f "bun.lockb" ]; then
          echo "❌ Project uses Bun only. Please remove other lockfiles and run 'bun install'"
          exit 1
        else
          echo "✅ Single lockfile policy enforced: bun.lockb only"
        fi

    - name: Install dependencies
      run: bun install --frozen-lockfile
    
    - name: Run TypeScript check
      run: bun run type-check
    
    - name: Lint assessment questions
      run: |
        node -e "
        const fs = require('fs');
        const path = require('path');
        
        // Read assessment questions file
        const questionsPath = 'src/data/assessmentQuestions.ts';
        const questionsContent = fs.readFileSync(questionsPath, 'utf8');
        
        console.log('🔍 Linting assessment questions for IPE compliance...');
        
        let errors = [];
        
        // Check for empty question arrays
        if (questionsContent.includes('options: []')) {
          errors.push('ERROR: Found empty options array - questions must have valid choices');
        }
        
        // Check for duplicate question IDs
        const idMatches = questionsContent.match(/'[a-z-0-9]+'/g);
        if (idMatches) {
          const ids = idMatches.map(id => id.replace(/'/g, ''));
          const duplicates = ids.filter((id, index) => ids.indexOf(id) !== index);
          if (duplicates.length > 0) {
            errors.push('ERROR: Duplicate question IDs found: ' + duplicates.join(', '));
          }
        }
        
        // Check for KPI tag presence
        if (!questionsContent.includes('kpiTag:')) {
          errors.push('WARNING: Questions missing KPI tags - analytics integration will fail');
        }
        
        // Check for adaptive trigger completeness
        const adaptiveTriggerCount = (questionsContent.match(/adaptiveTriggers/g) || []).length;
        const questionCount = (questionsContent.match(/id: '/g) || []).length;
        
        if (adaptiveTriggerCount < questionCount * 0.5) {
          errors.push('WARNING: Less than 50% of questions have adaptive triggers - user experience may feel scripted');
        }
        
        // Report results
        if (errors.length > 0) {
          console.log('❌ Assessment quality issues found:');
          errors.forEach(error => console.log('  ' + error));
          
          // Fail on errors, warn on warnings
          const hasErrors = errors.some(e => e.startsWith('ERROR'));
          if (hasErrors) {
            process.exit(1);
          }
        } else {
          console.log('✅ All assessment quality checks passed!');
        }
        
        console.log('📊 Assessment Statistics:');
        console.log('  Questions with adaptive triggers: ' + adaptiveTriggerCount);
        console.log('  Total questions: ' + questionCount);
        console.log('  Adaptive coverage: ' + Math.round((adaptiveTriggerCount / questionCount) * 100) + '%');
        "
    
    - name: Validate assessment types
      run: |
        # Ensure TypeScript compilation succeeds for assessment components
        npx tsc --noEmit --project tsconfig.json src/components/LivingEnvironmentQuiz.tsx
        npx tsc --noEmit --project tsconfig.json src/types/assessment.ts
        echo "✅ Assessment TypeScript validation passed"
    
    - name: Check component integration
      run: |
        node -e "
        const fs = require('fs');
        
        // Verify SafetyOutlet integration
        const quizContent = fs.readFileSync('src/components/LivingEnvironmentQuiz.tsx', 'utf8');
        if (!quizContent.includes('SafetyOutlet')) {
          console.log('❌ SafetyOutlet not integrated - IPE Pillar 2 compliance missing');
          process.exit(1);
        }
        
        // Verify KPI tracking
        if (!quizContent.includes('kpiCategory')) {
          console.log('❌ KPI tracking not implemented - IPE Pillar 6 compliance missing');
          process.exit(1);
        }
        
        console.log('✅ Component integration checks passed');
        "